[2024-10-04T08:15:28.868+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-04T08:15:28.886+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: uber_taxi_dag.run_pipeline manual__2024-10-04T08:15:26.060609+00:00 [queued]>
[2024-10-04T08:15:28.898+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: uber_taxi_dag.run_pipeline manual__2024-10-04T08:15:26.060609+00:00 [queued]>
[2024-10-04T08:15:28.899+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-04T08:15:28.917+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_pipeline> on 2024-10-04 08:15:26.060609+00:00
[2024-10-04T08:15:28.968+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=814) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T08:15:28.961+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'uber_taxi_dag', 'run_pipeline', 'manual__2024-10-04T08:15:26.060609+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/taxi_data_pipeline.py', '--cfg-path', '/tmp/tmpdn7yuuy7']
[2024-10-04T08:15:28.974+0000] {standard_task_runner.py:72} INFO - Started process 816 to run task
[2024-10-04T08:15:28.974+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask run_pipeline
[2024-10-04T08:15:29.081+0000] {task_command.py:467} INFO - Running <TaskInstance: uber_taxi_dag.run_pipeline manual__2024-10-04T08:15:26.060609+00:00 [running]> on host be9392c3401c
[2024-10-04T08:15:29.164+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='uber_taxi_dag' AIRFLOW_CTX_TASK_ID='run_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T08:15:26.060609+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T08:15:26.060609+00:00'
[2024-10-04T08:15:29.166+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-04T08:15:31.595+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/src/data_transformation.py:69 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-10-04T08:15:31.613+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/taxi_data_pipeline.py", line 18, in run_pipeline
    load_data(processed_tables)
  File "/opt/airflow/dags/src/data_storage.py", line 2, in load_data
    for table_name, table in processed_tables:
        ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
[2024-10-04T08:15:31.679+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=uber_taxi_dag, task_id=run_pipeline, run_id=manual__2024-10-04T08:15:26.060609+00:00, execution_date=20241004T081526, start_date=20241004T081528, end_date=20241004T081531
[2024-10-04T08:15:31.696+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-04T08:15:31.697+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task run_pipeline (too many values to unpack (expected 2); 816)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/taxi_data_pipeline.py", line 18, in run_pipeline
    load_data(processed_tables)
  File "/opt/airflow/dags/src/data_storage.py", line 2, in load_data
    for table_name, table in processed_tables:
        ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
[2024-10-04T08:15:31.765+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-04T08:15:31.810+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T08:15:31.811+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
